
liip_imagine:
    cache: ImagePathResolverService
    #data_loader: data_loader

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path:
            #web_root: "%kernel.project_dir%"

    loaders:
        # ...
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%"
                    - "%kernel.project_dir%/../"

    filter_sets :
        #cache : ~

        # the name of the "filter set"
        thumb :

            quality : 30