apiVersion: v1                  
kind: PersistentVolumeClaim     
metadata:                       
   name: pvc-sym-uploud
   namespace: ishtar
spec:                           
   accessModes:                  
   - ReadWriteOnce              
   resources:                   
      requests:                 
         storage: 5Gi   