apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: ishtar
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: gcr.io/yescloud/ishtarback
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pvc-sym-m
          mountPath: /var
      volumes:
      - name: pvc-sym-m
        persistentVolumeClaim:
          claimName: pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: ishtar
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache

